### ISSUE TITLE
vaspup2.0

### ISSUE THREAD

**Issue by kavanase** [sufyanshk/github-demo#1]
Hey @sufyanshk,
I noticed you forked my old VASP scripts repo. I just wanted to mention that, if you're doing `VASP` convergence tests, I recommend you use my newer package [vaspup2.0](https://github.com/kavanase/vaspup2.0) 😀. It makes it even simpler, and prints the results to the terminal for quick and easy analysis. Hope that helps!

**Comment by sufyanshk** [comment]
Hi @kavanase, 
I recently signed up on Github. I was exploring Github around and found out your repo.
Till few hours ago I didn't even know what "fork" means. I'll check it out.
Thanks for reaching out :) !
